{% set version = "0.5.0" %}

package:
  name: stateplane
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stateplane/stateplane-{{ version }}.tar.gz
  sha256: 9dc32567518ea6a5a15f276577a0763770541f9e1d2ba36efb4c19b25137fcfe

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - stateplane = stateplane.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pyproj >=3.2.0
    - shapely
    - gdal
    - importlib_resources

test:
  imports:
    - stateplane

about:
  home: https://github.com/fitnr/stateplane
  dev_url: https://github.com/fitnr/stateplane
  license: GPL-3.0-only
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Convert between state plane projections and long/lat
  description: |
    Get the local state plane projection for geographica coordinates, and
    automatically convert between coordinates and the local state plane
    projection. Includes state plane projections for the 50 states, DC, Puerto
    Rico, American Samoa, Guam and the US Virgin Islands.

extra:
  recipe-maintainers:
    - moorepants
