{% set version = "0.3.1" %}

package:
  name: stateplane
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stateplane/stateplane-{{ version }}.tar.gz
  sha256: 8cd99d0f0c5103a3ec1fbaeb300cdfd8833f5dc1289ee75022882fb11c296c51

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python
  entry_points:
    - stateplane = stateplane.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyproj >=1.9.4,<2
    - shapely >=1.5.1,<1.6
    - gdal >=2.0,<2.3

test:
  imports:
    - stateplane

about:
  home: https://github.com/fitnr/stateplane
  dev_url: https://github.com/fitnr/stateplane
  license: GPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Convert between state plane projections and long/lat'
  description: |
    Get the local state plane projection for geographica coordinates, and
    automatically convert between coordinates and the local state plane
    projection. Includes state plane projections for the 50 states, DC, Puerto
    Rico, American Samoa, Guam and the US Virgin Islands.

extra:
  recipe-maintainers:
    - moorepants
