travis:
  secure:
    BINSTAR_TOKEN: B+d3ejTZYMku2IuASi0gqfeIPIl5F9pZHmpRKCrlDMleamzkFa2mllRX2EnPe395uejgwo1miOifV7f9gL2QJrI/R6T0bNDURiy1gNkwKzd3p5ygAFtUzDtLQetXakICWJ9GcCjU+C0lqIqkN0xoMiB6OpSIfN/FHYRnrbC07aqqOc65fGKKy5gCqGYd09vqRDwqGGjI1hsxNS4eYpW5nzLV6FKPFj/Jdos4pgdRu3KxEYGw/LoikrI0d+4gqEon7f2hbAeKuNaZVRfKcCxRYT4wPXl7spdZuIuxZqKHCb1pADVDoUkLIi/O5q3HSgngYBMocjZOuECTKJo3lSHmHypjM27T3GQA8qhW7ceds4wwo5Ufafs8ipu3gNktYI2pgOb3AraJ603ttLhLP3KcjFj9x5sY/d4Lkk9aa8qzaNJ7b2F/Jv7KQ+IrP7OZi1ARGXWDmqw554HuKz01/uwcw0PECCKc0VU5GvzLoPMhnKkQD7+aA9km4f4OHSKBtp6azlX6ZWjLPet8ED0EiP3HhIrBCZJeuv09gqxm4SrBREFuBHXhftk66Kc4EODsYMmCkG+0WImqIcEcsrpsioXUHL8ynfly3aCWNW2vU/RmgZPRzB1DVHvEohMl0dy9PS96F7JSlRErZJ98pmg8/aaD/QcVZw/a/Lk+S22V343nClQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
